### ISSUE TITLE
Cell UMAP and Cluster Identifiers?

### ISSUE THREAD

**Issue by rwelling520** [Iwo-K/HSPCdynamics#5]
Hi, I'm hoping to take a look at the expression of various genes in various cell types within your dataset and I'm working directly with the 10X filtered_feature_bc_matrix.h5 files (sorry, I'm not overly familiar with containers and was having issues getting singularity to work, so would rather work with the more raw data). I'm really sorry if I'm just overlooking where this is, but I'm wondering if there is a place where I can find your UMAP embeddings and cluster assignments associated with each cell/barcode (minus the ones filtered out during your analysis)? Thank you for generating such an awesome dataset!

**Comment by Iwo-K** [comment]
Hi @rwelling520,
Thanks for reading our paper! This information is availablein the AnnData object (combined_filtered_landscape.h5ad) that we share on Mendeley data:
https://data.mendeley.com/datasets/vwg6xzmrf9/2
.h5ad files can be read using scanpy, cluster memberships are stored in the .obs attribute and UMAP coordinates under .obsm['X_umap']. The files also has a full gene expression matrix.

We also host an interactive app to allow easier exploration of the data, but unfortunately the server is down due to some technical issues at the University and we are still waiting for the fix. I will post here when this is back up.

**Comment by rwelling520** [comment]
Thank you!
